# docker-compose.yml
services:
  web:
    platform: linux/amd64
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  chrome:
      # platform: linux/amd64
      image: selenium/standalone-chrome:latest
      hostname: chrome
      privileged: true
      shm_size: 2g

  framework:
      platform: linux/amd64
      build: .
      depends_on: 
          - chrome

  cronjobs:
    build: .
    command: ["cron", "-f"]

volumes:
  postgres_data: